# ==================
# Environment
# ==================
environment: development

# ==================
# Base
# ==================
title: Janice Liu Illustration
description: Janice Liu (flutterdoodle) is a freelance children's illustrator and comic artist in Vancouver, Canada.
safe: true
exclude:
  - "node_modules"
  - "package.json"
  - "gulpfile.js"
  - "Gemfile"
  - "Gemfile.lock"
  
gems:
  - jekyll-redirect-from  
  
imgurl: 

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"